services:
  db:
    image: mysql:9.2.0
    container_name: web_store
    environment:
      MYSQL_ROOT_PASSWORD: 53cret
      MYSQL_DATABASE: bookstore
      MYSQL_USER: yu71
      MYSQL_PASSWORD: 53cret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
