spring:
  datasource:
    url: jdbc:mysql://localhost:3307/web_store?useSSL=false
    username: yu71
    password: 53cret
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: senkoShop@outlook.com
    password: Midostar10035
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  docker:
    compose:
      enabled: true

server:
  port: 8080

